CT logs #94
aau-network-security/richkit pull request #108
Opened 2020-03-24 10:02 UTC by gianmarcomennecozzi

2020-03-26 07:29 UTC, kidmose requested changes
Hi Giann, 
My points from yesterdays meeting;
 1. Seperation of cert.sh "API" interaction, e.g. in a file named like `richkit/retrieve/cert_sh.py`, which has a function to  get a list of "`CERT_SH_ID`"s for a domain and another function that can get the X.509 cert from the `CERT_SH_ID`.
 2. and the feature wrangling, e.g. named `richkit/retrieve/x509.py` which does the feature calculation and perhaps also has a class for X.509 certs.

Please ping me with another request for a review (or slack/skype) when you need me to check this out again, 
Have a nice day :)

2020-04-03 07:59 UTC, kidmose commented on richkit/retrieve/cert_sh.py
> +            self.certificates = json.loads(content)
hint: https://2.python-requests.org/en/master/api/#requests.Response.json

2020-04-03 09:03 UTC, kidmose requested changes
Nice work! 
There is a few points where the separation in in cert.sh and x.509 seems to need refinement, there is some dosctrings that needs to be added, and some minor commenting - all in my comments below.

If you get to it, you can check which makes sense and which requires some elaboration, so we can focus on the latter ones in our meeting later.

As always; Ping me for details or send me a new request for review.

2020-04-03 09:03 UTC, kidmose commented on richkit/retrieve/cert_sh.py
> +            if '@' not in cert.get('name_value'):
What does the `@` mean? could you add a comment?

2020-04-03 09:03 UTC, kidmose commented on richkit/retrieve/cert_sh.py
> +            if '@' not in cert.get('name_value'):
Again; why is '@` significant?

2020-04-03 09:03 UTC, kidmose commented on richkit/retrieve/cert_sh.py
> +                })
Similar to the earlier comment, this seems to be related to x.509 and not cert.sh, so the same as above applies.

2020-04-03 09:03 UTC, kidmose commented on richkit/retrieve/cert_sh.py
> +                })
All of these values seem to be fields of a x.509 certificate, so I would expect them to be in the `X509` class, coming in either as individual parameters, or as a single dict as a parameters, to `X509.__init__`.

2020-04-03 09:03 UTC, kidmose commented on richkit/retrieve/x509.py
> +class X509:
Please add docstrings for the X509 class and the method within.

2020-04-03 09:03 UTC, kidmose commented on richkit/retrieve/x509.py
> +    def __init__(self, cert_id):
... in particular; please document what `cert_id` is. (I'm unsure if it is the cert.sh id, which should not be present here because this models x509 certificates, and cert.sh IDs are not a part of that.)

2020-04-04 14:10 UTC, mrturkmen06 commented
After checking @kidmose's comments above, it seems, it requires some changes when it is done it can be merged.

2020-04-15 07:58 UTC, kidmose requested changes
Thanks for the new changes - that was a good step forward :)

There are still some things that needs to be addressed, as per the comments I've added. In general, three types of changes are required still;
 1. Add the missing dosctrings that I marked with a comments.
 2. Add test cases for the methods in `X509`, also marked with comments.
 3. I looked at you reasoning for skipping results containing an "@", and I still don't understand it, so this needs more work too.

I suggest that you try to address the more trivial comments (1 and 2, I presume), and have another look at those that are a bit more challenging (3, I presume), and then we should take a call and discuss how to move forward on this.
Will you have the time to look into this, and have the call on Friday?

2020-04-15 07:58 UTC, kidmose commented on richkit/retrieve/cert_sh.py
> +            if '@' not in cert.get('name_value'):
Looking at the example given in the comments, it seems that there actually is a valid certificate at the URL and it does contain a CN (`commonName = *.hosted.jivesoftware.com`) which I believe means that it is a certificate for a domain (actually many domains, as it has a wildcard), and therefore relevant.

Could you make it clearer why it makes sense to skip all certs where 'name_value` contains an "@"?

2020-04-15 07:58 UTC, kidmose commented on richkit/retrieve/x509.py
> +    """
FYI and not necessarily something you have to change now; 

I was thinking that it made sense to make a class that is only modelling certificates based on the [established standard](https://en.wikipedia.org/wiki/X.509), with an implementation that is free from any ties to a specific API like https://crt.sh. This would make reusing, when we move away from crt.sh much easier. It seems that both the `X509` and the `DomainCertificates` classes are inherently tied to crt.sh using their IDs and API. Maybe there is some aspect that I don't get, that makes this necessary, and the current implementation seems work, so we can leave where it is for now :)

2020-04-15 07:58 UTC, kidmose commented on richkit/retrieve/cert_sh.py
> +class DomainCertificates:
Please add a docstring explaining the purpose of having this class.

2020-04-15 07:58 UTC, kidmose commented on richkit/retrieve/cert_sh.py
> +    def __init__(self, domain):
Please add a docstring, including the `domain` parameter.

2020-04-15 07:58 UTC, kidmose commented on richkit/retrieve/x509.py
> +    def __init__(self, cert_id):
Please format the commend on line 19 as a docstring for `__init__`.

2020-04-15 07:58 UTC, kidmose commented on richkit/retrieve/x509.py
> +def unique_apex(sans):
Missing test case. Please add the file `richkit/test/retrieve/test_x509.py` with a test method named `test_unique_apex(self)`, containing relevant tests.

2020-04-15 07:58 UTC, kidmose commented on richkit/retrieve/x509.py
> +def unique_sld(sans):
Missing test case. Please add the file `richkit/test/retrieve/test_x509.py` with a test method named `test_unique_sld(self)`, containing relevant tests.

2020-04-15 07:58 UTC, kidmose commented on richkit/retrieve/x509.py
> +def lcs(x, y):
Missing test case. Please add the file `richkit/test/retrieve/test_x509.py` with a test method named `test_lcs(self)`, containing relevant tests.

2020-04-21 06:34 UTC, mrtrkmn approved these changes

2020-04-21 08:55 UTC, kidmose approved these changes

2020-04-23 10:05 UTC, merged