minimal fix to current situation
aau-network-security/richkit pull request #120
Opened 2020-04-01 15:06 UTC by mrturkmen06

- fixes #119

2020-04-01 15:08 UTC, mrturkmen06 commented
It could be nice to merge this changes before merging others #118 , #115, @kidmose

2020-04-02 07:01 UTC, kidmose commented on richkit/test/lookup/test_util.py
> +            return True
To me, something like this reads easier and makes better use of the testing framework:

    self.assertIsInstance(s.get_age(), datetime.timedelta)

Is there a reason for not doing that?
(Reference: https://docs.python.org/3/library/unittest.html#assert-methods)

2020-04-02 07:15 UTC, kidmose requested changes

2020-04-02 07:15 UTC, kidmose commented on richkit/test/lookup/test_util.py
> -        self.assertFalse(obj.is_outdated())
I'm unsure if it is ok to remove this check.
Can you explain why it should be removed and not replaced with something like `self.assertFalse(XXX.get_age() > timedelta(weeks=1))`
(If `is_outdated()` really should be removed, as per above comment)

2020-04-02 07:15 UTC, kidmose commented on richkit/lookup/util.py
> -        return self.get_age() > timedelta(weeks=1)
This function has a purpose; It should make it clear that the Maxmind DBs are updated weekly. 
I realise that there should be a comment/docstring that explains this, and a link (Which i don't have handy anymore).
I don't see a reason for removing it, so could you either revive it or make it clear why it should go away?

.. and may I ask you the favour of adding said docstring? Thanks a lot! :)

2020-04-02 08:45 UTC, mrturkmen06 commented on richkit/lookup/util.py
> -        return self.get_age() > timedelta(weeks=1)
I agree, it had a purpose, however, that check can be done `if self.get_age() > timedelta(weeks=1):` in [line 49](https://github.com/aau-network-security/richkit/blob/eaf809fb72c7fc8bba9273a2372e764a58f71099/richkit/lookup/util.py#L49) and I could not see any other usage of that function. 

I am just wondering that if we are already using `get_age()` function in all other functions within that file what would be the difference when `is_outdated` removed and test case reformatted ?

2020-04-02 08:45 UTC, mrturkmen06 commented on richkit/test/lookup/test_util.py
> -        self.assertFalse(obj.is_outdated())
In my opinion, it is absolutely ok to remove it from test cases, since there is only one thing  which is important to test is `get_age()` , other part of the code is just built-in check, for  `test_is_outdated` test case.

2020-04-02 09:26 UTC, mrturkmen06 commented on richkit/test/lookup/test_util.py
> +            return True
Test to [get_age()](https://github.com/aau-network-security/richkit/blob/67b16077aa1d88523a282029c7797a337ae51094/richkit/test/lookup/test_util.py#L107) function is already implemented over there.

2020-04-02 09:29 UTC, gianmarcomennecozzi reviewed
The changes that Ahmet made are fine. What i have done was correct as well, but in this case we have removed some lines of code and we can still test the `is_outdated()` function.

2020-04-03 07:30 UTC, kidmose commented on richkit/lookup/util.py
> -        return self.get_age() > timedelta(weeks=1)
Looking only at the functionality, I fully agree.
As for capturing in the code the fact that the acceptable age is up to 1 week, this is still lacking on documentation/reference on why it exactly that. `is_outdated` seemed like a good place to document that, but as your points are valid, I can also see this aspect addressed with some useful comments on/around l49.

(Consider yourself coming back to this code in a year, or someone else picking it up. You/they would have no idea why the age is compared to 1 week, and that bit is important for correctness of returned values)

2020-04-04 14:07 UTC, merged