docker file for test purposes added
aau-network-security/richkit pull request #125
Opened 2020-04-06 11:35 UTC by mrturkmen06

- `Dockerfile.test` added for running test cases in docker environment instead of on machine. 
-  Although, it might have drawbacks like running only on ubuntu, it has some advantages as well, running docker image for test purposes, eliminates all other problems regarding to environment.

2020-04-08 10:14 UTC, gianmarcomennecozzi reviewed
Good job man. i have tested it in local and it's working very well :)

2020-04-15 07:01 UTC, kidmose requested changes
Nice work!

I have some concerns about entering a secret (License key) into a version controlled file, as per comment in ` .github/local-test/run-test.sh`. I'd would like to see this addressed before we merge. I've added a bunch of comments where I expect the solution to this also should be reflected.

Another couple of comments might require some small changes, or perhaps I simply need a bit more explanation (perhaps with comments here).

Thanks!

2020-04-15 07:01 UTC, kidmose commented on .github/local-test/run-test.sh
> +export MAXMIND_LICENSE_KEY="<licence_key_should_be_added_here>"
Requiring secrets to be entered into files that are under VCS is bad because it creates risk of accidentally committing a secret.

Can you do this in way that does not require editing a version controlled files by adding a secret? Perhaps using a docker `ENV` variable in combination with `docker run -e`?

2020-04-15 07:01 UTC, kidmose commented on .github/local-test/run-test.sh
> +FLAKE8_ERROR_LIMIT=25
Having to maintain this number in two places is twice the work and there is a risk that they get out of sync.
Is it possible to make both this script and the github actions that does the similar check use a simple file that holds this number? 

(I'm thinking: `FLAKE8_ERROR_LIMIT=$(cat flake8_error_limit.txt)`)

2020-04-15 07:01 UTC, kidmose commented on Dockerfile.test
> +# otherwise it may fail for lookup test cases
See previous comment on secrets in version controlled files.

2020-04-15 07:01 UTC, kidmose commented on Dockerfile.test
> +COPY .git /richkit/.git
It is not obvious to me why `.git` has to go into the docker image. 
Could you explain this?

2020-04-15 07:01 UTC, kidmose commented on README.md
> + - The only thing to add is just `MAXMIND_LICENCE_KEY` in `.github/local-test/run-test.sh` at line 3. It is required to pass the test cases for `lookup` module.
See previous comment on secrets in version controlled files.

2020-04-15 07:01 UTC, kidmose commented on richkit/test/retrieve/test_symantec.py
> +    def test_read_categorized_file(self, file_path=CAT_URLS_FILE):
Could please educate me on how a parameter with a default value (`file_path`) for a test method makes sense.
Is there a relevant scenario where you actually get to set this parameter to something other that the default value?

I don't know of such, and it seems to me that replacing `file_path` with `CAT_URLS_FILE` (except where it is used as a param name, obviously) in this function would be effectively the same, with a simpler and easier to understand method declaration.

2020-04-15 12:19 UTC, mrturkmen06 commented on .github/local-test/run-test.sh
> +export MAXMIND_LICENSE_KEY="<licence_key_should_be_added_here>"
I totally agree, my bad :) I forgot to do so, will make changes and re-request for review.

2020-04-15 12:22 UTC, mrturkmen06 commented on Dockerfile.test
> +COPY .git /richkit/.git
oh, yeah, I was thinking to add `check-branch-name` step to local testing environment however apparently I forgot to add it, that's why I was copying `.git` into docker image.

2020-04-15 13:08 UTC, mrturkmen06 commented on .github/local-test/run-test.sh
> +FLAKE8_ERROR_LIMIT=25
I am not quite sure about it.

2020-04-16 06:38 UTC, kidmose requested changes
Nice and clean! 

Two test cases seems to have been removed, see comments. 
Once those are addressed I'm pretty confident this is all good :+1:

2020-04-16 06:38 UTC, kidmose commented on richkit/test/retrieve/test_symantec.py
> -        self.assertIsInstance(read_categorized_file(), dict)
This removed chunk tests how `read_categorized_file` behaves when `CAT_URLS_FILE` is missing, by checking that a `dict` is returned when we know that `CAT_URLS_FILE` isn't there (Just after the `unlink`).

Has this been moved somewhere I overlooked? If so please point me to it, and otherwise please reinstate it here (With the old line 33 modified to `Path(CAT_URLS_FILE).unlink()` I guess..)

2020-04-16 06:38 UTC, kidmose commented on richkit/test/retrieve/test_symantec.py
> -        CAT_URLS_FILE.touch()
Similarly to the above, this removed chunk makes sure that `CAT_URLS_FILE` is present, but empty, and on the lines below we test that a `dict` with zero entries is returned.

If this is moved somewhere else, could you point me to it, or otherwise reintroduce this chunk?

2020-04-16 06:41 UTC, kidmose commented on .github/local-test/run-test.sh
> +FLAKE8_ERROR_LIMIT=25
Fair enough. Lets leave it at that and pick it up if it becomes a problem :)

2020-04-20 08:15 UTC, kidmose approved these changes
Again, nicely done :+1:
 Thanks for keeping up with me when I'm nitpicking about quality :)

2020-04-20 09:32 UTC, merged